---
title: "dnr_eda"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(lubridate)
library(readxl)
library(sf)
library(stringr)
library(janitor)
library(tmap)
library(zoo)

iowa_crs <- 26976
```


## Chemical readings EDA

```{r}
DNR <- read_xlsx("./data/IowaDNR_2019_Data_Merged.xlsx",
                sheet = "WK6-15-2") %>% 
  separate(Label, c("week", NA), "-") %>% 
  clean_names()
```

```{r}
DNR %>% view()
```

```{r}
DNR %>% 
  ggplot(aes(week, microcystin)) +
  geom_point() + 
  geom_line(group = 1) + 
  facet_wrap(~ environmental_location, ncol = 4)
```

## Autocorrelations

```{r}
DNR %>% 
  filter(environmental_location == "Brushy Creek Beach") %>% 
  select(microcystin) %>% 
  acf()
```


```{r}
DNR %>% 
  split(.$environmental_location) %>% 
  map(~acf(.$microcystin, main = unique(.$environmental_location)))
```

## Station readings EDA

```{r}
# station_readings <- read.csv("./data/station_data-precip-only.csv") %>% 
station_readings <- read.csv("./data/station_data.csv") %>%
  separate(DATE, c('year', 'month', 'day'), "-") %>% 
  clean_names()
```

```{r}
station_readings %>% view()
```

```{r}
station_readings %>% 
  filter(station == "USC00138688" & month == '06') %>% 
  view()
```

```{r}
station_readings %>% 
  filter(station == "USC00138688" & month == '06') %>% 
  select(station, name, year, month, day, prcp) %>% 
  mutate(prcp_5dma = rollmean(prcp, k = 5, fill = NA, align = 'right'))
```
